### PR TITLE
[202205] [Backport] Add media assignment options to Application Advertisement

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Description
Add media assignment options to Application Advertisement

#### Motivation and Context
Add media assignment options to Application Advertisement

#### How Has This Been Tested?
Manual test

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca , all checkers passed, could you please help merge this?

**Pull request merged**
