### PR TITLE
Convert the tx/rx power unit to the dBm unit

### PR DESCRIPTION
**Pull request by chiourung**
#### Description

The tx/rx power unit in the eeprom is mW, and the tx/rx power unit for the API is dBm. It should be converted to the dBm in get_transceiver_bulk_status().

---------

Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>

### CODE REVIEW

**Review by prgeor — DISMISSED** [review]

**Comment by prgeor** [comment]
@chiourung can you add unit test for code-coverage?

**Review by mihirpat1 — COMMENTED** [review]
Can you please add testcases to improve code coverage for the changeset since the PR check is failing due to this currently.

**Comment by chiourung** [comment]
> Can you please add testcases to improve code coverage for the changeset since the PR check is failing due to this currently.

Done

**Comment by chiourung** [comment]
> @chiourung can you add unit test for code-coverage?

Done

**Review by mihirpat1 — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@yxieca @StormLiangMS can you cherry pick this fix to 202305 and 202205

**Pull request merged**
