### PR TITLE
Add flag to read partial VDM

### PR DESCRIPTION
**Pull request by chiourung**
#### Description
It spend much time to read full VDM.
Add flag to read VDM for real value, threshold or flag.

#### How Has This Been Tested?

original:
get_transceiver_info 0:00:00.370253
get_transceiver_bulk_status 0:00:03.990558
get_transceiver_status 0:00:03.600985
get_transceiver_pm 0:00:01.761066
get_transceiver_threshold_info 0:00:03.137684

After this patch:
get_transceiver_info 0:00:00.317530
get_transceiver_bulk_status 0:00:02.210669
get_transceiver_status 0:00:01.608513
get_transceiver_pm 0:00:01.671107
get_transceiver_threshold_info 0:00:01.609460

### CODE REVIEW

**Comment by prgeor** [comment]
@chiourung can you add code coverage/unit test since the build is failing

**Review by mihirpat1 — APPROVED** [review]

**Review by prgeor — DISMISSED** [review]

**Comment by prgeor** [comment]
@chiourung can you resolve the merge conflict?

**Comment by prgeor** [comment]
@chiourung can you please rebase and resolve merge conflict

**Review by prgeor — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
This PR causes an issue https://github.com/sonic-net/sonic-buildimage/issues/18468

**Pull request merged**
