### PR TITLE
Added new RegBitsFields

### PR DESCRIPTION
**Pull request by prgeor**
#### Description
Added new field RegBitsField. This will allow read/write single or more bits in a group of fields.

#### Motivation and Context
This allows to write fields that are 1bit or more but < 1 Byte

#### How Has This Been Tested?
Added unit test for different bit sizes.

### CODE REVIEW

**Comment by prgeor** [comment]
@andywongarista can you review?

**Review by mihirpat1 — APPROVED** [review]

**Review by andywongarista — APPROVED** [review]

**Review by vdahiya12 — APPROVED** [review]

**Comment by lguohan** [comment]
lgtm, maybe add a few more description about why we need such new field.

**Review by lguohan — APPROVED** [review]

**Comment by prgeor** [comment]
@StormLiangMS @yxieca please help cherry pick

**Comment by StormLiangMS** [comment]
@prgeor is this bug fix or enhancement?

**Comment by StormLiangMS** [comment]
Missing this will cause advance submodule build failure.

**Pull request merged**
