### PR TITLE
Update additional PN for Innolight and Eoptolink

### PR DESCRIPTION
**Pull request by AnoopKamath**
#### Description
Update additional PN for Innolight and Eoptolink

#### How Has This Been Tested?
Check if no optoe errors or other xcvrd errors seen

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by AnoopKamath** [comment]
@prgeor @mihirpat1 : Can you please help cherry pick this to 202311 and 202305 ?

**Comment by mihirpat1** [comment]
@StormLiangMS @yxieca @bingwang-ms Can you please help to cherry-pick this to 202305, 202311 and 202405?
MSFT ADO - 28551599

**Comment by shivuv** [comment]
@prgeor  @mihirpat1 : Can you pleas help to get this PR cherry picked into 202405 ?

**Comment by mihirpat1** [comment]
> @prgeor @mihirpat1 : Can you pleas help to get this PR cherry picked into 202405 ?

@bingwang-ms Can you please help with this?

**Comment by AnoopKamath** [comment]
@bingwang-ms : can you please help cherry pick this into 202405 ?

**Pull request merged**
