### PR TITLE
Cdb fw upgrade

### PR DESCRIPTION
**Pull request by CliveNi**
[Cloudlight] QSFP-DD FW upgrade doesn't work (#257)

#### Description
* Fix : cdb1_chkstatus crash when i2c NACK or timeout.
* Feat : Waiting a delay in "run_fw_image" to ensure it is really executed.
* Feat : Returning a error package when get none in "get_module_fw_info".
* Fix : Using real length to replace fixed number in "block_write_epl" function.

#### Motivation and Context
* I2C of transceiver might NACK or stretching when FW upgrade, assuming "None" means "CdbIsBusy" until timeout.
* "run_fw_image" will be executed after a delay which according to run command, waiting the delay in "run_fw_image" to avoid sending another command before it really be executed.
* CDB commands will maybe cause few seconds NACK or stretching on i2c bus depend on implementation of module, handling this situation for compatible with different implementation.
* To avoid a wrong epl length used in module.

### CODE REVIEW

**Comment by aravindmani-1** [comment]
Could you please upload Unit Test logs?.

**Comment by CliveNi** [comment]
> Could you please upload Unit Test logs?.

For cmis.py

<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="Clive-Ni" name="pytest" skipped="0" tests="173" time="7.656" timestamp="2022-09-05T15:19:37.905463"><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_model[1234567890-1234567890]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_model[ABCD-ABCD]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_vendor_rev[0.0-0.0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_vendor_rev[1.2-1.2]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_serial[100000000-100000000]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_type[QSFP-DD Double Density 8X Pluggable Transceiver-QSFP-DD Double Density 8X Pluggable Transceiver]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_connector_type[LC-LC]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_hardware_revision[mock_response0-0.1]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_cmis_rev[mock_response0-5.0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_state[ModuleReady-ModuleReady]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_fault_cause[No Fault detected-No Fault detected]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_active_firmware[mock_response0-0.1]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_inactive_firmware[mock_response0-0.1]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_temperature[mock_response0-55.0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_temperature[mock_response1-N/A]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_temperature[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_voltage[mock_response0-3.0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_voltage[mock_response1-N/A]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_voltage[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_is_flat_memory[False-False]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_temperature_support[False-True]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_voltage_support[False-True]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_los_support[mock_response0-True]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_cdr_lol_support[mock_response0-True]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_cdr_lol[mock_response0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_cdr_lol[mock_response1-expected1]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_cdr_lol[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_cdr_lol[mock_response3-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_los[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_los[mock_response1-expected1]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_los[mock_response2-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_los[mock_response3-None]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_cdr_lol_support[mock_response0-True]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_cdr_lol[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_cdr_lol[mock_response1-expected1]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_cdr_lol[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_cdr_lol[mock_response3-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_power_flag[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_power_flag[mock_response1-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias_flag[mock_response0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias_flag[mock_response1-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_power_flag[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_power_flag[mock_response1-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_output_status[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_output_status[None-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_output_status[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_output_status[None-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias_support[mock_response0-True]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias[mock_response1-expected1]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias[mock_response2-expected2]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_bias[mock_response3-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_power_support[mock_response0-True]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_power[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_power[mock_response1-expected1]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_power[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_power_support[mock_response0-True]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_power[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_power[mock_response1-expected1]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_rx_power[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_fault_support[mock_response0-True]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_fault[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_fault[mock_response1-expected1]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_fault[mock_response2-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_fault[mock_response3-None]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_los_support[mock_response0-True]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_los[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_los[mock_response1-expected1]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_los[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_los[mock_response3-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable_support[mock_response0-True]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable[mock_response1-expected1]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable[mock_response2-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable[mock_response3-None]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_tx_disable[True]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_tx_disable[False]" time="0.001" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable_channel[mock_response0-0]" time="0.024" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable_channel[mock_response1-N/A]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_disable_channel[mock_response2-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_tx_disable_channel[0-input_param0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_tx_disable_channel[0-input_param1]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_tx_disable_channel[None-input_param2]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_power_override" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_power_override" time="0.001" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_thresholds_support[False-True]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_lpmode_support[None-False]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_lpmode_support[Power Class 1-False]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_lpmode_support[Power Class 8-True]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_power_override_support" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_type[sm_media_interface-sm_media_interface]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_electrical_interface[400GAUI-8 C2M (Annex 120E)-400GAUI-8 C2M (Annex 120E)]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_interface[sm_media_interface-400ZR-400ZR]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_interface[nm_850_media_interface-100GE BiDi-100GE BiDi]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_interface[passive_copper_media_interface-Copper cable-Copper cable]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_interface[active_cable_media_interface-Active Loopback module-Active Loopback module]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_interface[base_t_media_interface-1000BASE-T (Clause 40)-1000BASE-T (Clause 40)]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_media_interface[ABCD-ABCD-Unknown media interface]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_is_coherent_module[Copper cable-False]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_is_coherent_module[400ZR-True]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_lane_count[8-8]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_lane_count[1-1]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_interface_technology[C-band tunable laser-C-band tunable laser]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_lane_assignment_option[1-1]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_lane_assignment_option[1-1]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_active_apsel_hostlane[mock_response0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_tx_config_power[-10--10]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_output_loopback[1-True]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_output_loopback[None-None]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_input_loopback[1-True]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_media_input_loopback[None-None]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_output_loopback[0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_output_loopback[None-None]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_input_loopback[0-expected0]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_host_input_loopback[None-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_aux_mon_type[194-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_aux_mon_type[None-None]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_laser_temperature[mock_response10-mock_response20-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_laser_temperature[mock_response11-mock_response21-expected1]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_laser_temperature[mock_response12-mock_response22-expected2]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_laser_TEC_current[mock_response10-mock_response20-expected0]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_laser_TEC_current[mock_response11-mock_response21-expected1]" time="0.009" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_laser_TEC_current[mock_response12-mock_response22-None]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_config_datapath_hostlane_status[mock_response0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_datapath_state[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_dpinit_pending[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_dpinit_pending[None-None]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_supported_power_config[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_reset_module" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_reset" time="2.015" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_low_power[lpmode0]" time="1.023" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_loopback_capability[mock_response0-expected0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_loopback_capability[mock_response1-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_loopback_capability[mock_response2-None]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_loopback_mode[none-mock_response0]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_loopback_mode[host-side-input-mock_response1]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_loopback_mode[host-side-output-mock_response2]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_loopback_mode[media-side-input-mock_response3]" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_loopback_mode[media-side-output-mock_response4]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_loopback_mode[none-None]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_vdm[mock_response0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_vdm[mock_response1-expected1]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_firmware_fault_state_changed[1-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_level_flag[mock_response0-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_module_level_flag[mock_response1-None]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_run[1-1-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_run[1-64-expected1]" time="0.007" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_commit[1-expected0]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_commit[64-expected1]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_upgrade[abc-mock_response0-expected0]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_upgrade[abc-mock_response1-expected1]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_upgrade[abc-mock_response2-expected2]" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_module_fw_upgrade[abc-mock_response3-expected3]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_info[mock_response0-None]" time="0.010" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_info[mock_response1-expected1]" time="0.008" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_bulk_status[mock_response0-expected0]" time="0.010" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_bulk_status[mock_response1-expected1]" time="0.011" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_threshold_info[mock_response0-expected0]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_threshold_info[mock_response1-None]" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_threshold_info[mock_response2-expected2]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_threshold_info[mock_response3-None]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_status[mock_response0-expected0]" time="0.015" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_status[mock_response1-expected1]" time="0.012" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_loopback[mock_response0-expected0]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_loopback[mock_response1-expected1]" time="0.005" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_transceiver_loopback[mock_response2-expected2]" time="0.006" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_cable_len" time="0.001" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_datapath_init" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_datapath_deinit" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_application_advertisement" time="0.002" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_application" time="0.003" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_set_application" time="0.004" /><testcase classname="tests.sonic_xcvr.test_cmis.TestCmis" name="test_get_error_description" time="0.003" /></testsuite></testsuites>

**Comment by CliveNi** [comment]
> Could you please upload Unit Test logs?.

[test_cmis-results.txt](https://github.com/sonic-net/sonic-platform-common/files/9487675/test_cmis-results.txt)
[test_cmisCDB-results.txt](https://github.com/sonic-net/sonic-platform-common/files/9487681/test_cmisCDB-results.txt)

**Review by aravindmani-1 — DISMISSED** [review]

**Comment by aravindmani-1** [comment]
@prgeor could you please review this PR?.

**Review by aravindmani-1 — COMMENTED** [review]
It'd be better if you could get the UT logs done inside the switch.

**Comment by prgeor** [comment]
@CliveNi can you check the code coverage failure

**Comment by CliveNi** [comment]
> @CliveNi can you check the code coverage failure

Done, attachment is new UT log.
[test_cmis-results.txt](https://github.com/sonic-net/sonic-platform-common/files/9525278/test_cmis-results.txt)

**Review by prgeor — APPROVED** [review]

**Pull request merged**
