### PR TITLE
Modify get_host_lane_assignment_option to return value based on application id

### PR DESCRIPTION
**Pull request by mihirpat1**
The changes with this PR needs to be merged along with sonic-net/sonic-platform-daemons#342

#### Description

The API get_host_lane_assignment_option doesn't return the host_lane_assignment_options using the application id and always returns value from Application Descriptor 1 (AppSel = 1)

#### Motivation and Context

The API get_host_lane_assignment_option will now take the AppSel id as the input and would return the host_lane_assignment_option from the relevant Application Descriptor

#### How Has This Been Tested?

Testcase summary
Please refer to the test details attached to sonic-net/sonic-platform-daemons#342

### CODE REVIEW

**Comment by mihirpat1** [comment]
@prgeor @jaganbal-a @keboliu @shyam77git - It will be great if you can help in reviewing this PR

**Comment by shyam77git** [comment]
Please add UT cases and logs

**Comment by prgeor** [comment]
@shyam77git @jaganbal-a please review

**Comment by prgeor** [comment]
@keboliu please review

**Comment by mihirpat1** [comment]
> Please add UT cases and logs

I have updated it now.

**Review by prgeor — APPROVED** [review]

**Pull request merged**
