### PR TITLE
[202305] Add new SSD type support 

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Description

Backport PR https://github.com/sonic-net/sonic-platform-common/pull/390 to 202305

Add new SSD vendor "Swissbit" support

#### Motivation and Context

Add new SSD vendor "Swissbit" support

#### How Has This Been Tested?

Unit test
Manual test

### CODE REVIEW

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
@Junchao-Mellanox could you help to take a look at this build failure?

**Comment by Junchao-Mellanox** [comment]
Hi @StormLiangMS , fixed

**Comment by dgsudharsan** [comment]
@StormLiangMS Can you please help merge this?

**Pull request merged**
