### PR TITLE
[202205] Fix issue: should use 'Value' column to calculate the health percentage for Virtium SSD

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Backport commits:

07ccd27 Fix issue: should use 'Value' column to calculate the health percentage
6d2d7a3 [ssd_generic] Get health status from Remaining_Life_Left field for virtium SSD (#344)
feb5036 [SSD] deduce vendor name from part number (#322)

#### Description

Currently, we are using "Low Raw" column to calculate SSD health, but "Value"column should be used according to vendor document.

#### Motivation and Context

Fix issue that SSD health display wrong value

#### How Has This Been Tested?

Manual test
Unit test

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor  and @yxieca , could you please help review this?

**Comment by liat-grozovik** [comment]
@prgeor @yxieca please help to approve/merge this to 202205

**Review by prgeor — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca suggest to merge to 202205. can you please review?

**Comment by volodymyrsamotiy** [comment]
@yxieca, it is CLI only and doesn't require any sonic-mgmt test

**Pull request merged**
